AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MirrorLingo - Personalized Spanish Learning App

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Globals:
  Function:
    Timeout: 15
    Runtime: nodejs18.x
    Environment:
      Variables:
        PHRASES_TABLE: !Ref PhrasesTable
        BEDROCK_MODEL_ID: anthropic.claude-3-haiku-20240307-v1:0

Resources:
  # DynamoDB Table for storing user phrases and analysis
  PhrasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub MirrorLingo-Phrases-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: phraseId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: phraseId
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # API Gateway
  MirrorLingoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub MirrorLingo-Users-${Environment}
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub MirrorLingo-Client-${Environment}
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  # Lambda Functions
  PhraseHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub MirrorLingo-PhraseHandler-${Environment}
      CodeUri: ../backend/dist/
      Handler: handlers/phrase-handler.handler
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PhrasesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        CreatePhrase:
          Type: Api
          Properties:
            RestApiId: !Ref MirrorLingoApi
            Path: /phrases
            Method: POST
        GetPhrases:
          Type: Api
          Properties:
            RestApiId: !Ref MirrorLingoApi
            Path: /phrases
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${MirrorLingoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub MirrorLingo-ApiUrl-${Environment}
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub MirrorLingo-UserPoolId-${Environment}
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub MirrorLingo-UserPoolClientId-${Environment}
